version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile.backend
    volumes:
      - ../server:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
